[inputs.terraform]
url = "github:stackbuilders/nixpkgs-terraform"

[[overlays]]
terraform = "default"

[nix-config]
extra-substituters = "https://nixpkgs-terraform.cachix.org"
extra-trusted-public-keys = "nixpkgs-terraform.cachix.org-1:8Sit092rIdAVENA3ZVeH9hzSiqI/jng6JiCrQ1Dmusw="
