imports = [ "./bat.nix" ]

[[commands]]
package = "foo"

[[commands]]
package = "moo"

[[commands]]
package = "hello-unfree"

[[commands]]
name = "check"
help = "test environment"
command = """
hello-unfree
foo
moo
bat
"""