# Custom nixpkgs distribution
[inputs.nixpkgs]
url = "github:nixos/nixpkgs/nixpkgs-unstable"
[inputs.devshell]
url = "github:numtide/devshell"
inputs.nixpkgs.follows = "nixpkgs"


# Allow devshell.toml to load relative imports
[inputs.source]
url = "path:./"
flake = false

# Custom exposed systems
[inputs.systems]
url = "path:./systems.nix"
flake = false

# non-flake dependency read by bat.nix
[inputs.file]
url = "path:./file"
flake = false

# example flake exposing two overlays
[inputs.something]
url = "path:./something"

# load overlays
[[overlays]]
something = "foo"
[[overlays]]
something = "moo"

[nix-config]
allowUnfree = true # because we want hello-unfree
